// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gizunguswdzufaiprwsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpenVuZ3Vzd2R6dWZhaXByd3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzgyMTcsImV4cCI6MjA2NDU1NDIxN30.sDlZ4EO3go_V6MOobXu2PFa5GUjUDz9BAdrunGHtkOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);