name: Generate Game Results Every Minute

on:
  schedule:
    - cron: "*/1 * * * *"  # Every 1 minute
  workflow_dispatch:       # Optional manual trigger

jobs:
  call-edge-function:
    runs-on: ubuntu-latest

    steps:
      - name: Call Supabase Edge Function to generate game results
        env:
          SUPABASE_EDGE_KEY: ${{ secrets.SUPABASE_EDGE_KEY }}
        run: |
          curl -X POST https://rdhfmkqxkycdjkystkbt.supabase.co/functions/v1/generate-game-results \
            -H "Authorization: Bearer ${SUPABASE_EDGE_KEY}" \
            -H "Content-Type: application/json"
